### PR TITLE
A few tweaks?

### PR DESCRIPTION
**Pull request by OmgImAlexis**
1. Adds `*.tgz` to the gitignore list.
2. Removes `tslib`
3. Adds `tsup`
4. Adds `del-cli` to handle rm-rf on Windows
5. Removes default exports

This would be a breaking change as the main export is now `{ Client }` instead of `Client`.

### CODE REVIEW

**Comment by thislooksfun** [comment]
Alright this is a lot to take in at once. Could you explain why you feel each of those changes is necessary?

**Comment by OmgImAlexis** [comment]
1. Good practise otherwise `npm pack` could end up being included with a `git add -A`
2. Unneeded bloat for the little it adds
3. Faster bundling
4. Allows the script to work on windows. rm isn’t a command in cmd.
5. Using default exports is a bad practise, google “why not use to default exports” if you need more info.

**Comment by thislooksfun** [comment]
1. Not a terrible idea, but not strictly needed since the npm deploy is automated. I'll add it anyway though just to be safe.
2. I disagree, it reduces the number of repeated boilerplate definitions in the generated code (though you bringing it up did make me realize I wasn't using it correctly, so thank you)
3. Not necessary, the default `tsc` works just fine and I'd rather not change it unless there is a *really* compelling reason to do so.
4. Good idea.
5. I also disagree on this. This seems like a personal preference issue and my preference is to have modules expose what you'd expect. Making every single export named makes the imports more cluttered for no real benefit unless you're working without any IDE, and come on, it's 2021.

Thanks for your interest in the project, if you think of other improvements don't hesitate to reach out! Though in future please keep each PR to one single change, it makes it way easier to review.

**Comment by thislooksfun** [comment]
To expand on point 5: The only default export from `snoots` as a module is `Client`, which is intentional since the name of it really doesn't matter and some people might want to call it something else (yes I know about the `import { x as y }` pattern, but this way is cleaner for this case). Every other export from the module is named. Internally I use default exports a lot because it makes sense to me, so that's how I've done it. But even then I remap them to named exports in all the `index.ts` files so that I can import them as named where that is more logical.

**Comment by OmgImAlexis** [comment]
> To expand on point 5: The only default export from `snoots` as a module is `Client`, which is intentional since the name of it really doesn't matter and some people might want to call it something else (yes I know about the `import { x as y }` pattern, but this way is cleaner for this case). Every other export from the module is named. Internally I use default exports a lot because it makes sense to me, so that's how I've done it. But even then I remap them to named exports in all the `index.ts` files so that I can import them as named where that is more logical.

I’d highly suggest reading into this. Default exports are a anti patten and shouldn’t be used. You can even see that by the fact you’re needing reexport and change around defaults. Just use names. This feels like you’re choosing personal preference over a standard in a sense. 💁‍♀️

**Comment by thislooksfun** [comment]
> I’d highly suggest reading into this.
I did.

> This feels like you’re choosing personal preference over a standard in a sense. 💁‍♀️
Except that I'm not. Having a single default export with named helper exports is standard across every single npm module I've ever used. I'll consider switching internal export defaults to named exports, but as it stands it's a large refactor that only affects maintainers. Since I'm the only maintainer I'm writing it to my personal coding standards, which allow for default exports. You are free to structure your own code however you would like, but until such time as other maintainers get brought into this project I'd rather spend the effort that would go into that kind of refactor on fixing bugs and implementing new features.

**Comment by thislooksfun** [comment]
@OmgImAlexis I would like to apologize for my dismissal of removing default exports. I still think that default exports do make sense for tiny modules that only *have* one export, like `camelcase` or `left-pad`, but even then snoots has clearly far outgrown that scale and it will only continue to get larger, and any benefits I previously saw are now far outweighed by the benefits of having all exports be named. This PR can no longer be merged, but I have made a new commit that does so (actually using `Co-Authored-By:` this time, sorry about that), which will be pushed shortly.

**Pull request closed without merging**
