### PR TITLE
refactor: make RedditListing generic

### LINKED ISSUE #88: RedditListing.children is not always of type RedditObject[]
### What happened?

```typescript
export interface RedditListing {
  after?: string;
  before?: string;
  children: RedditObject[];
  dist?: number;
  modhash?: string;
}
```

`RedditListing.children` is defined as type `RedditObject[]`, however, not all listings contain a field `children` of type `RedditObject[]`. This is most readily observed in the wiki revisions listing being worked on in #87, where `children` is an array of POD.

### Reproduction steps

n/a

### Snoots Version

all

### Node Version

n/a

### Logs

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by thislooksfun**
This (hopefully) fixes #88.

### CODE REVIEW

**Comment by thislooksfun** [comment]
@JamesxX I listed you as a co-author on this change since you jumpstarted the work in 8b6ccd524b05436f4dc785b48095ce33115a2db9. Is that alright with you?

**Comment by JamesxX** [comment]
@thislooksfun any chance we can chat on discord?

**Comment by thislooksfun** [comment]
> [If] you use default generic parameters like in [8b6ccd5](https://github.com/thislooksfun/snoots/commit/8b6ccd524b05436f4dc785b48095ce33115a2db9), you might be able to save yourself making an extra type alias, and modifying too many files.

That's true, but doing it this way makes it more explicitly generic. Using a default generic parameter like in 8b6ccd524b05436f4dc785b48095ce33115a2db9 it would indeed work with fewer changes, but would mean that code like this
```
export function fakeListingAfter(after: string): RedditListing {
  return { after, children: [] };
}
```
would still compile, despite the fact that it should really be generic as well. Not having the default parameter means every place we were using/will use `RedditListing` we now need to make a conscious decision of "should this be strongly typed, or should it be generic?", which should lead to fewer changes down the line. This way touches some more places now, but it means we can be certain going forwards that anywhere that takes or returns a non-generic `RedditListing` is doing so intentionally.

> @thislooksfun any chance we can chat on discord?

While I'm not oppose to it in theory, I also would prefer to keep all snoots discussion as public as possible (with the obvious exception of any active vulnerabilities, but those shouldn't be reported on Discord either). Do you have a specific need that would be better suited for a Discord conversation?

**Comment by JamesxX** [comment]
Was more about progressing my other PRs, having lots of branches locally makes it an absolute pain making new commits.

**Pull request merged**
