### PR TITLE
feat: thumbnail implementation and documentation

### PR DESCRIPTION
**Pull request by cachho**
I tried to reimplement the thumbnail.

Other than uncommenting lines I added documentation and `nsfw` as a possible type.

I tried looking around but couldn't figure out how far you would like to abstract:

I would prefer if nsfw and self posts returned `undefined` instead of a `nsfw` or `self` as a string. So you'd have a src url or undefined. How are the nsfw and self string going to be helpful? No one is going to use thumbnail for type checking, there are better ways to do that. But that's just my opinion, maybe I'm missing something.

Another thought I had was using a type like
```
type Thumbnail = {
    url: string;
    height: number;
    width: number;
}
``` 
which would be optional. But I didn't find a precedence for something like that in your code.

### CODE REVIEW

**Comment by cachho** [comment]
did you get a chance to review this?

**Comment by JamesxX** [comment]
The dude doesn't ever look at pull requests. I made 3 implementing modmail, wiki, and modnotes, and they just got ignored. I merged them into one so I could keep working on more stuff but he just out of hand said no big pull requests and shut them all down.

I wouldn't waste your time man

**Comment by cachho** [comment]
> I wouldn't waste your time man

do you have an alternative?

**Comment by JamesxX** [comment]
Just fork it, hell if you do, I'll add my code as a pull request to yours

**Comment by cachho** [comment]
> Just fork it, hell if you do, I'll add my code as a pull request to yours

I did, https://github.com/cachho/snoots

**Comment by thislooksfun** [comment]
> Did you get a chance to review this?

I have not yet, no, and given Reddit's current situation regarding the direction of their API and the attitude of their CEO I have exactly zero motivation at the moment to work on this or anything else Reddit related.

---

> The dude doesn't ever look at pull requests.

I have a full-time job as a software developer. My entire day, 9-5, is spent programming for work. The last thing I want to do most days after work is even more programming. Additionally I have other responsibilities, and obligations that take up much of my already limited free time. Forgive me if the MIT-licensed project I started for fun in my spare time doesn't manage to get my full attention 24/7.

I do look at PRs. And I feel bad about leaving them. But I also have an obligation to ensure that all the code I put my name on meets my standards of quality, and that requires detailed reviews of all the code I merge. Most of it meets those standards, but I need to make sure, and I take that responsibility seriously. Unfortunately this means that I am not able to dedicate nearly as much time as I would like to performing these detailed reviews, which means that they go neglected for far too long, and for that I do deeply apologize.

> I made 3 implementing modmail, wiki, and modnotes, and they just got ignored. I merged them into one so I could keep working on more stuff but he just out of hand said no big pull requests and shut them all down.

Let's review the timeline and details on that, shall we?

- Wed Dec 28, you opened #83 (9 commits, +408 -15)
- Tues Jan 3 I reviewed #83, requesting some changes
- Wed Jan 4 you push to #83 fixing the issue
- Wed Jan 4 you also create #87 (24 commits, +1023 -26)
- Sat Jan 7 you open #94 (29 commits, +1813 -26)
- Sun Jan 8 I sit down to re-review #83 and start reviewing the already very large #87 and #94, only to see that you closed all 3 of those and had instead opened #95 (41 commits, +2,085 −27).

After seeing the "Mega pull request" I then [politely requested](https://github.com/thislooksfun/snoots/pull/95#issuecomment-1374872388) that you re-open the three smaller PRs so they could be reviewed, approved, and merged individually, and even [offered to help with the work](https://github.com/thislooksfun/snoots/pull/95#issuecomment-1374887323) to get it merged faster. [You refused, instead repeatedly asking to contact me via Discord](https://github.com/thislooksfun/snoots/pull/95#issuecomment-1374891665). The discussion ended with you saying "[I'll need a few days as I'll need to recreate the PR.](https://github.com/thislooksfun/snoots/pull/95#issuecomment-1374910903)"

The total time between your first PR and its first review was < 1 week, and the time between the fix for that review and your other two PRs and me trying to review them all was 4 days. In the time since you posted that last message about recreating the PRs (which should still be as simple as re-opening #83, #87, and #94) and now, you have made 0 new PRs and given me 0 status updates. I had assumed that you had moved on and forgotten about this package.

---

> Just fork it, hell if you do, I'll add my code as a pull request to yours

👍 This is why it's open source under the MIT license.

**Comment by JamesxX** [comment]
We've all got jobs mate, 9-5 sounds pretty cushy, I'm a researcher and last week my days were 8am to 9.30pm, but still got time to open my emails, see your reply, and type a quick response.

**Comment by cachho** [comment]
Respectfully, maybe you should consider giving @JamesxX maintainer permissions. He seems to know what he's doing. As he says, we all got jobs, we all got different interests, and the idea of open source is also to spread the workload. I guess if you say you're done with this we either have to fork or you gotta bring in new people for the project to continue. I'm also open to join, I just have to admit that I'm still learning. Branching off/forking doesn't seem like the smartest idea, considering there's so much left to do and we should work together.

On a side note, if API requests cost money even for the first request, that would be something that would force me to reconsider my "business plan" too. But I could not find concrete information yet.

**Pull request closed without merging**
