### PR TITLE
Mega pull request (Modnotes, Modmail, and wiki)

### PR DESCRIPTION
**Pull request by JamesxX**
I'm coallescing my pull requests into a single request, as It's at the point where I'm having to reimplement the same thing several times. I'd also like to push forward with creating unit tests, which may require some additional dependencies. To see any previous discussions, see #83 , #87 , #94 .

### Features

- New modmail controller that exposes the following
  - `modmail.getConversations( subreddit, after?, limit?, sort?, state? )`, to fetch an array of recent conversations. These are minimally detailed.
  - `modmail.createNewConversation`
  - `modmail.getConversation( conversationID, markRead)`, to fetch a modmail conversation in detail. This makes use of an extended class to add these extra details
  - `modmail.approveParticipant( conversationID )`
  - `modmail.archiveConversation( conversationID )`
  - `modmail.disapproveParticipant( conversationID )`
  - `modmail.highlightConversation( conversationID )`
  - `modmail.unhighlightConversation( conversationID )`
  - `modmail.muteParticipant( conversationID, duration )`
  - `modmail.tempBanParticipant( conversationID, duration)`
  - `modmail.unarchiveConversation( conversationID )`
  - `modmail.unbanParticipant( conversationID )`
  - `modmail.unmuteParticipant( conversationID )`
  - `modmail.getSubreddits( )`
  - `modmail.markAsRead`
  - `modmail.markAsUnread`
  - `modmail.getUnreadCount`
- A `ModmailConversation` class to handle these new functions, along with data sent back by reddit
- A `ModmailConversationDetailed` class to handle conversations where extra details have been fetched, including messages, moderator actions, etc. This class extends `ModmailConversation`
- New Modnote controller that exposes the following
  - `modnote.deleteNote( id, subreddit, user )`
  - `modnote.getNotes( subreddit, user, filter?, limit? before? )` for fetching notes made on a user
  - `modnote.createNote( subreddit, user, note, label?, redditID?)` for creating a note
  - `modnote.getRecent()`
  - `modnote.getSubreddit` utility function
  - `modnote.getUser` utility function
  - `modnote.getOperator` utility function
  - `modnote.getContent` utility function
- The `ModeratorNote` class for dealing with individual moderator notes OOP.
- New Wiki controller that exposes the following
  - `wiki.addEditor`
  - `wiki.removeEditor`
  - `wiki.editPage`
  - `wiki.toggleVisibility`
  - `wiki.revertPage`
  - `wiki.getPages`
  - `wiki.getRecentChanges`
  - `wiki.getRecentChangesForPage`
  - `wiki.getSettings`
  - `wiki.changeSettings`
  - `wiki.getPage`
- A Wiki class for dealing with individual wiki pages OOP
- Listing classes for wiki revisions

### Not yet implemented
- [ ]  `modmail.replyToConversation`.

### Weird stuff
For the life of me, I can't seem to get the `api/mod/bulk_read` API endpoint to return anything other than Error 404. It remains implemented in `modmail.bulkMarkRead`, but as far as I can tell, this endpoint no longer exists.

Hope to get some feedback on this. Seems to be taking ages to get this pull requests looked at though.

### CODE REVIEW

**Comment by JamesxX** [comment]
### Non-breaking change
Added dotenv and dotenv-expand as development dependencies to allow for unit tests to be published without exposing secrets.

**Comment by JamesxX** [comment]
### Non-breaking change
Implement `modmail.highlightConversation( conversationID )`

**Comment by thislooksfun** [comment]
Please do not create mega pull requests. If you are implementing multiple features they should each have their own PR. The larger a PR is the harder it is to review and adjust. If you need to use some base changes in multiple of your PRs then create one base PR with those common changes, and have your other PRs branch off of that.

**Comment by thislooksfun** [comment]
Additionally, regarding commit messages:
- Please do not use `[skip ci]` unless absolutely necessary (it virtually never is).
- Please only use `feat:`, `fix:`, and `perf:` for changes that are exposed to the user of this package. For example, `Gateway::delete()` is an internal method, so adding it isn't a new feature. It should be a `chore`.

**Comment by JamesxX** [comment]
Skipped CI because of the new unit tests I added not having secrets loaded, and didn't wish to get spammed with emails. It's a shame this is closed, as I feel I had added a good chunk to the library, but I understand if you would rather not merge someone else's work.

**Comment by JamesxX** [comment]
Other reason for the bundling of the PR was my merging into my own main branch changing the already-made pull requests that seemingly hadn't had much attention. I don't know how to undo this, so I remade this one, which made sense. I'm not going to spend any time trying to separate out these commits into different branches.

**Comment by thislooksfun** [comment]
> I understand if you would rather not merge someone else's work.

I'm absolutely fine with merging other people's work, but I do this in my free time, of which I have precious little. Large PRs like this one are way harder to review properly, which means they take more of my time, and thus are far less likely to be reviewed and approved in a timely manner. 


> Skipped CI because of the new unit tests I added not having secrets loaded, and didn't wish to get spammed with emails. 

Unit tests shouldn't needs secrets, and e2e tests are currently blocked by trying to figure out a way to do it without running into the rate limit (see #11).


>  I'm not going to spend any time trying to separate out these commits into different branches.

That's a shame. If you are able to open smaller PRs I'd happily merge them. If not, would you be willing to let me do so? I'm perfectly happy to split the commits myself, provided I can also make any small tweaks that are needed to fit the project's goals. You'd be credited, of course.

---

I can also see how that last reply seems to conflict with the first, so let me explain: _reviewing_ a PR of this size is hard, because if I find any changes that need to be made (code, docs, commits, etc.) I need to:

1. identify that a change needs to happen
2. identify what the change is
3. determine if it's worth asking the contributor to do, or it can be merge as-is and fixed later
4. find a way to communicate the desired change to the contributor
5. wait for them to make the change
6. review the new changes, starting over at step 1
7. repeat until there are finally no more pending changes

The feedback loop on that is slow and imprecise. It works fine for simple changes, so smaller PRs are totally fine, but on a PR of this size it's quite slow, which is a drag for both of us—we both want it to be merged, after all!

Doing the work myself though, using your work as a starting point means I can replace steps 3-7 with just "make the change myself", which is way faster.

**Comment by JamesxX** [comment]
> I'm absolutely fine with merging other people's work, but I do this in my free time, of which I have precious little. Large PRs like this one are way harder to review properly, which means they take more of my time, and thus are far less likely to be reviewed and approved in a timely manner.

I understand, however, the merging of these pull requests was in part due to the fact that the smaller ones were not looked at.

> Unit tests shouldn't needs secrets, and e2e tests are currently blocked by trying to figure out a way to do it without running into the rate limit (see https://github.com/thislooksfun/snoots/issues/11).

Regardless of the name you want to call it by, that's the reason for the [skip ci] tag on those commits. As you didn't want to talk on discord, I had no way to ask you about it.

> That's a shame. If you are able to open smaller PRs I'd happily merge them. If not, would you be willing to let me do so? I'm perfectly happy to split the commits myself, provided I can also make any small tweaks that are needed to fit the project's goals. You'd be credited, of course.

There were smaller PRs open, which weren't happily merged. Equally, what is the difference between you doing the changes yourself and keeping the pull request open? Keeping the pull request open would be much more transparent, surely.

> I can also see how that last reply seems to conflict with the first, so let me explain: reviewing a PR of this size is hard, because if I find any changes that need to be made (code, docs, commits, etc.) I need to:

The other pull requests can easily be found by following the links in the first comment, or in the "closed" tab on the pull requests screen. They are smaller.

> The feedback loop on that is slow and imprecise. It works fine for simple changes, so smaller PRs are totally fine, but on a PR of this size it's quite slow, which is a drag for both of us

Again, this pull request contains the same commits as those previously. You would be reviewing the same quantity of code.

> we both want it to be merged, after all!

I'm genuinely not so sure. I tried to get in touch with you in several different ways and have heard nothing.

> Doing the work myself though, using your work as a starting point means I can replace steps 3-7 with just "make the change myself", which is way faster.

Please see comments on transparency made above

**Comment by thislooksfun** [comment]
> I understand, however, the merging of these pull requests was in part due to the fact that the smaller ones were not looked at.

Again, I have limited time where I am both not engaged with some other commitment _and_ have the focus and motivated needed to review PRs. I am a software developer for my full-time job, so when I get off work usually the _last_ thing I want to do is more code review. Because of that I usually review longer PRs (like all of the ones listed) on the weekends, when I have more motivation. #83 and #87 were last updated 4 days ago, and #94 was created yesterday. I was planning to start reviewing them today, but they were all closed before I got a chance to do so.

> Regardless of the name you want to call it by, that's the reason for the [skip ci] tag on those commits. As you didn't want to talk on discord, I had no way to ask you about it.

Talking to me on Discord has nothing to do with this. The fact that those commits were breaking tests should have been the signal that they were not a good fit to be merged.

> There were smaller PRs open, which weren't happily merged. Equally, what is the difference between you doing the changes yourself and keeping the pull request open? Keeping the pull request open would be much more transparent, surely.

I detailed the difference in my last message. Since you seem to be so focused on getting things done quickly, I thought you would appreciate the quicker solution. If you really want to go down the single giant PR route, I will re-open this and review it properly, but there's a good chance it will take several review sessions, which means it will likely take several weeks to get merged.

> The other pull requests can easily be found by following the links in the first comment, or in the "closed" tab on the pull requests screen. They are smaller.

Yes, and since you closed them I now can't review them in that smaller form.

> Again, this pull request contains the same commits as those previously. You would be reviewing the same quantity of code.

Overall it's the same quantity, yes, but the portioning matters. There's a difference between eating an entire cake in one sitting vs eating it one slice at a time over several days.

> I'm genuinely not so sure. I tried to get in touch with you in several different ways and have heard nothing.

You mentioned me in a couple places within a day or two of creating the PR in the first place. That's not "several different ways", and in the world of free open source software, that's a really short turnaround time. Again, I am doing this _in my spare time_ because I _want_ to. I have no obligations to update this (or any of my other projects), and no hard timelines to stick to, so I take my time with them to make sure they are done _right_ while preventing me from burning out. I get that it's frustrating to not have your PRs merged instantly, but unless a project is being worked on full-time, it's gonna take a few days (at least) sometimes.

**Comment by JamesxX** [comment]
I'll need a few days as I'll need to recreate the PR. In meantime, please do check your email, or chat on discord. Would make all of this easier.

**Pull request closed without merging**
