### PR TITLE
Modnotes pull request

### PR DESCRIPTION
**Pull request by JamesxX**
I'm putting this pull request here so others might review it, despite it still being a work in progress. This stems from issue #77 where I outlined the API endpoints and made some discussion on design choices.

### Main changes
**Changes to the gateway class** (6c3ad77fe5b45467775e51ba74d869c7d17f511e). A `delete` method has been added to the gateway class for the purposes of making delete requests for the modnote endpoint. On migration from got to native fetch, this will be trivial to update also. In the meantime, it follows closely the design of the get function.

**Moderator notes API**. All 4 endpoints for mod notes have been implemented in a separate controller. None of the exposed functions thus far have been used in other classes such as the subreddit object. 

### To Do

- [x] Implement 4th endpoint (GET /api/mod/notes/recent). I haven't begun looking at what the response is like from the API, but I imagine it will make design decisions difficult so I have chosen to put it off for as long as possible. Ultimately, I think it should be implemented at the top level, as it covers many subreddits and users concurrently.
- [ ] Expose the added functions through the subreddit object class. Fetching, creating and deleting.

### CODE REVIEW

**Comment by JamesxX** [comment]
The added features are now fully documented. They are as yet only exposed through the client class, as I'm not sure about adding multiple controllers to the subreddit class (as a design choice or even how I'd go about it in the first place) so I will leave it to others.

**Comment by thislooksfun** [comment]
Thank you for making this PR! Apologies in the delay getting to it.

> I'm not sure about adding multiple controllers to the subreddit class

Each object class, including `Subreddit`, should only have one `Controller` attached to it. However, `Controller`s can [reference other controllers](https://github.com/thislooksfun/snoots/blob/4b9edad44ebf5bc4d8ae0028ce5f8178f1a12f95/src/reddit/post/controls.ts#L135), so it's totally possible to add aliases to the `Subreddit` class. That being said, that kind of optimization can definitely wait for a later revision.

**Review by thislooksfun — CHANGES_REQUESTED** [review]
There are a few comment style problems here. I updated the eslint configuration to make it catch things like that sooner. Could you please rebase against `master` and fix the new errors?

**Comment by JamesxX** [comment]
Any bump on this?

**Pull request closed without merging**
